export default [
    'Sunny',
    'Partly cloudy',
    'Cloudy',
    'Overcast',
    'Mist',
    'Patchy rain possible',
    'Patchy rain nearby',
    'Patchy snow nearby',
    'Patchy sleet nearby',
    'Patchy freezing drizzle nearby',
    'Thundery outbreaks in nearby',
    'Blowing snow',
    'Blizzard',
    'Fog',
    'Freezing fog',
    'Patchy light drizzle',
    'Light drizzle',
    'Freezing drizzle',
    'Heavy freezing drizzle',
    'Patchy light rain',
    'Light rain',
    'Moderate rain at times',
    'Moderate rain',
    'Heavy rain at times',
    'Heavy rain',
    'Light freezing rain',
    'Moderate or heavy freezing rain',
    'Light sleet',
    'Moderate or heavy sleet',
    'Patchy light snow',
    'Light snow',
    'Patchy moderate snow',
    'Moderate snow',
    'Patchy heavy snow',
    'Heavy snow',
    'Ice pellets',
    'Light rain shower',
    'Moderate or heavy rain shower',
    'Torrential rain shower',
    'Light sleet showers',
    'Moderate or heavy sleet showers',
    'Light snow showers',
    'Moderate or heavy snow showers',
    'Light showers of ice pellets',
    'Moderate or heavy showers of ice pellets',
    'Patchy light rain in area with thunder',
    'Moderate or heavy rain in area with thunder',
    'Moderate or heavy rain with thunder',
    'Patchy light snow in area with thunder',
    'Moderate or heavy snow in area with thunder',
    'wind-beaufort-12',
    'wind-beaufort-11',
    'wind-beaufort-10',
    'wind-beaufort-9',
    'wind-beaufort-8',
    'wind-beaufort-7',
    'wind-beaufort-6',
    'wind-beaufort-5',
    'wind-beaufort-4',
    'wind-beaufort-3',
    'wind-beaufort-2',
    'wind-beaufort-1',
    'Wind',
    'Temperature',
    'Humidity',
    'Clear',
] as const;
